server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: oauth, db, jpa, redis
  session:
    store-type: jdbc