server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8080
  ssl:
    enabled: true
    key-alias: local
    key-store: classpath:private.p12
    key-store-type: PKCS12
    key-store-password: 123456
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: oauth, db, jpa, redis
  session:
    store-type: jdbc